trigger:
- main

pool:
  name: 'bankafeh-self'

variables:
  - group: AWS_KEYS

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'

- script: |
    terraform init -upgrade
    terraform plan -out=tfplan
    terraform apply -auto-approve tfplan
  displayName: 'Terraform Deploy'
  env:
    AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY)
    AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_KEY)